---
title: "covariate - excised text"
author: "Jeff Walker"
date: "11/4/2019"
output: html_document
---



a change score is conditional
One might reasonably expect that if mice are randomized into two groups, then the expected difference in percent change from baseline is zero, or $\mathrm{E}[percent change] = 0$ This is unconditionally true but not conditionally true. That is, if we ignore initial fat weight, the expected difference is zero. But, **the expected difference is also conditional on the initial difference in fat weights**, or $\mathrm{E}[percent change|initial difference] \ne 0$. More specifically, the expected difference is opposite in sign but proportional in magnitude to the initial difference. This conditional expectation is a consequence of regression to the mean. If the first measure of a random variable is extreme, the second measure will tend to be less extreme. And, if a second measure is extreme, the first measure will tend to be less extreme. 

Despite random treatment assignment, the mean initial fat weight of the *ob/ob* group was 1.2SD less than the mean initial weight of the *+/+* group. By contrast, the mean final weight of the *ob/ob* group was 0.06SD larger than the mean final weight of the *+/+* group. This first difference is an extreme measure. The second is extremely close to the expectation if there is no treatment effect. Because the initial difference in weight is unusually negative, the expected difference in percent change will be unusually positive.

This dependency between difference in percent change from baseline and difference in initial weight is easy to simulate. Simply
