---
title: "45 lmm-blocking"
output: html_notebook
---
```{r setup}
library(ggplot2)
library(reshape2)
library(ggpubr)
library(data.table)
library(emmeans)
library(lme4)
library(lmerTest)


```

simulation. 10 replicates of two treatment levels in 6 plots. The plots are "batches" or "clusters".

```{r fake_data}
all_treatments_per_batch <- function(sigma=1, sigma_b0=1, sigma_b1=1, beta_0=10, beta_1=1, n_block=6, n_subsamp=10){
  if(sigma_b0==0){sigma_b0 <- 1e-10}
  if(sigma_b1==0){sigma_b1 <- 1e-10}
  fake_data <- data.table(NULL)
  # this is a slow, inefficient way to build the data but should be easy to follow
  for(i in 1:n_block){
    #  random intercept for each plot
    beta_0i <- rnorm(1, mean=0, sd=sigma_b0)
    beta_1i <- rnorm(1, mean=0, sd=sigma_b1)
    # the response in the control and treated groups
    y1 <- beta_0 + beta_0i + (beta_1 + beta_1i)*0 + rnorm(n_subsamp, mean=0, sd=sigma)
    y2 <- beta_0 + beta_0i + (beta_1 + beta_1i)*1 + rnorm(n_subsamp, mean=0, sd=sigma)
    # combine into a data.table and rbind to end of fake_data
    fake_data <- rbind(fake_data,
                       data.table(Treatment=rep(c("Cn","T+"), each=n_subsamp),
                                  subsample=rep(1:n_subsamp, 2),
                                  block=letters[i],
                                  Y=c(y1, y2))
    )
  }
  
  fake_data[, block:=factor(block)]
  return(fake_data)
}
    
```

```{r}
one_treatment_per_batch <- function(sigma=1, sigma_b0=1, sigma_b1=1, beta_0=10, beta_1=1, n_batch=6, n_reps=10, missing=1){
  # missing controls number of missing observations
  n_levels <- 2 # number of treatment_levels
  fake_data <- data.table(NULL)
  # this is a slow, inefficient way to build the data but should be easy to follow
  batch_ij <- 0
  for(j in 1:n_levels){
    for(i in 1:n_batch){
      batch_ij <- batch_ij+1
      #  random intercept for each plot
      if(sigma_b0 > 0){
        beta_0ij <- rnorm(1, mean=0, sd=sigma_b0)
      }else{
        beta_0ij <- 0
      }
      # the response in the control and treated groups
      if(j == 1){
        y <- beta_0 + beta_0ij + beta_1*0 + rnorm(n_reps, mean=0, sd=sigma)
      }else{
        y <- beta_0 + beta_0ij + beta_1*1 + rnorm(n_reps, mean=0, sd=sigma)
      }
      # combine into a data.table and rbind to end of fake_data
      fake_data <- rbind(fake_data,
                         data.table(Treatment=rep(j, 10),
                                    replicate=1:n_reps,
                                    batch=paste("p", batch_ij, sep="_"),
                                    Y=y)
      )
    }
    
  }
  fake_data[, Treatment:=factor(ifelse(Treatment==1, "Cn", "Tr"))]
  fake_data[, batch:=factor(batch)]
  return(fake_data)
}

```


```{r all-treatments-per-batch-simulation}
fd <- all_treatments_per_batch(sigma=1, sigma_b0=1, sigma_b1=0, beta_1=1, n_batch=6, n_reps=5)
complete_pooling <- lm(Y~Treatment, data=fd)
no_pooling <- lmList(Y ~ Treatment | batch, fd)
partial_pooling <- lmer(Y~Treatment + (Treatment|batch), data=fd)
aggregate_pooling <- lm(Y~Treatment, data=fd[, .(Y=mean(Y)), by=.(Treatment, batch)])
coef(summary(no_pooling))
coef(summary(complete_pooling))
coef(summary(partial_pooling))
coef(summary(aggregate_pooling))
anova(partial_pooling)
anova(aggregate_pooling)

coef(summary(lm(Y~Treatment, data=fd)))
coef(summary(lmer(Y~Treatment + (1|batch), data=fd)))
coef(summary(lmer(Y~Treatment+(Treatment|batch), data=fd)))

b_no_pooling <- coef(no_pooling) # y~Treatment conditional on batch
b_no_pooling_dt <- data.table(batch=row.names(no_pooling), no_pooling)
b_complete_pooling <- coef(complete_pooling)
b_partial_pooling <- coef(partial_pooling)

no_pooling
complete_pooling
partial_pooling$batch
```

```{r all-per-batch-plot}
fd <- all_treatments_per_batch(sigma=1, sigma_b0=1, beta_1=1, n_batch=6, n_reps=10)
fit.lm <- lm(Y~Treatment, data=fd)
fd[, lm.r:=residuals(fit.lm)]
ggerrorplot(x="batch", 
            y="lm.r", 
            color="Treatment",
            data=fd, 
            desc_stat = "mean_sd", 
            palette = "jco",
            position = position_dodge(0.3), 
            add=c("jitter")
             )

fit.lmm <- lmer(Y~Treatment + (1|batch), data=fd)
fd[, lmm.r:=residuals(fit.lmm)]
ggerrorplot(x="batch", 
            y="lmm.r", 
            color="Treatment",
            data=fd, 
            desc_stat = "mean_sd", 
            palette = "jco",
            position = position_dodge(0.3), 
            add=c("jitter")
             )

```

```{r one-treatment-per-batch}

fd <- one_treatment_per_batch(sigma=1, sigma_b0=1, beta_1=1, n_batch=6, n_reps=10)
coef(summary(lm(Y~Treatment, data=fd)))
coef(summary(lmer(Y~Treatment + (1|batch), data=fd)))

df_no_pooling <- lmList(Y ~ Treatment + (Treatment | batch), fd) %>% 
  coef() %>% 
  # Subject IDs are stored as row-names. Make them an explicit column
  rownames_to_column("Subject") %>% 
  rename(Intercept = `(Intercept)`, Slope_Days = Days) %>% 
  add_column(Model = "No pooling")

```


```{r one-per-batch-plot}
fd <- one_treatment_per_batch(sigma=1, sigma_b0=1, beta_1=1, n_batch=6, n_reps=10)
fit.lm <- lm(Y~Treatment, data=fd)
fd[, lm.r:=residuals(fit.lm)]
ggerrorplot(x="batch", 
            y="lm.r", 
            color="Treatment",
            data=fd, 
            desc_stat = "mean_sd", 
            palette = "jco",
            position = position_dodge(0.3), 
            add=c("jitter")
             )

fit.lmm <- lmer(Y~Treatment + (1|batch), data=fd)
fd[, lmm.r:=residuals(fit.lmm)]
ggerrorplot(x="batch", 
            y="lmm.r", 
            color="Treatment",
            data=fd, 
            desc_stat = "mean_sd", 
            palette = "jco",
            position = position_dodge(0.3), 
            add=c("jitter")
             )

```

```{r simulation}
set.seed(1)
n_plots <- 6 # number of batches or clusters
n_reps <- 10 # number of replicates within each cluster
sigma <- 1
sigma_b0 <- 1
beta_0 <- 10
beta_1 <- 0.5
Y <- matrix(nrow=n_reps*2, ncol=n_plots) # wide format, the response of the 10 replicates in each plot
fake_data <- data.table(NULL)
# this is a slow, inefficient way to build the data but should be easy to follow
for(i in 1:n_plots){
  #  random intercept for each plot
  beta_0j <- rnorm(1, mean=0, sd=sigma_b0)
  # the response in the control and treated groups
  y1 <- beta_0 + beta_0j + beta_1*0 + rnorm(n_reps, mean=0, sd=sigma)
  y2 <- beta_0 + beta_0j + beta_1*1 + rnorm(n_reps, mean=0, sd=sigma)
  # combine into a data.table and rbind to end of fake_data
  fake_data <- rbind(fake_data,
                     data.table(Treatment=rep(c("Cn","T+"), each=10),
                                replicate=rep(1:n_reps, 2),
                                plot=paste("p",i,sep="_"),
                                Y=c(y1, y2))
                     )
}

fake_data[, plot:=factor(plot)]
fake_data[, group:=paste(Treatment, plot, sep="-")]
ggerrorplot(x="plot", 
            y="Y", 
            color="Treatment",
            data=fake_data, 
            desc_stat = "mean_sd", 
            palette = "jco",
            position = position_dodge(0.3), 
            add=c("jitter")
             )

# dcast(dt_long, ID+condition~location, value.var='length') # perfect
fake_data_wide <- dcast(fake_data, plot+replicate ~ Treatment, value.var='Y')
ggline(x="plot",
       y=c("Cn", "T+"), 
       data=fake_data_wide, 
       add=c("mean_sd", "jitter"), 
       merge=TRUE,
       palette = "jco"
       ) +
  NULL

fit.lm <- lm(Y~Treatment, data=fake_data)
coef(summary(fit.lm))
fake_data[, lm_r:=residuals(fit.lm)]
fake_data_wide <- dcast(fake_data, plot+replicate ~ Treatment, value.var='lm_r')
ggline(x="plot",
       y=c("Cn", "T+"), 
       data=fake_data_wide, 
       add=c("mean_sd", "jitter"), 
       merge=TRUE,
       palette = "jco"
       ) +
  geom_hline(yintercept=0, color="red")

fit.lmm <- lmer(Y~Treatment + (1|plot), data=fake_data)
coef(summary(fit.lmm))
fake_data[, lmm_r:=residuals(fit.lmm)]
fake_data_wide <- dcast(fake_data, plot+replicate ~ Treatment, value.var='lmm_r')
ggline(x="plot",
       y=c("Cn", "T+"), 
       data=fake_data_wide, 
       add=c("mean_sd", "jitter"), 
       merge=TRUE,
       palette = "jco"
       ) +
  geom_hline(yintercept=0, color="red")

fit.lm2 <- lm(Y~plot+Treatment, data=fake_data)
coef(summary(fit.lm2))


```


```{r sim2}
# lmm coefficients vs. lmm anova with interaction ss as denominator

set.seed(1)
n_block_set <- 6 # number of batches or clusters
n_subsamples_set <- 10 # number of replicates within each cluster

niter <- 1000
p <- matrix(NA, nrow=niter, ncol=3)
colnames(p) <- c("lm.factorial", "lm.add", "lmm")
for(iter in 1:niter){
  fd <- all_treatments_per_batch(n_block=n_block_set, n_subsamp=n_subsamples_set, beta_1=0)
  fit.lm <- lm(Y~Treatment*block, data=fd)
  fit.lm2 <- lm(Y~Treatment+block, data=fd)
  fit.lmm <- lmer(Y~Treatment + (Treatment|block), data=fd)
  p[iter,] <- c(coef(summary(fit.lm))["TreatmentT+", "Pr(>|t|)"],
                coef(summary(fit.lm2))["TreatmentT+", "Pr(>|t|)"],
                coef(summary(fit.lmm))["TreatmentT+", "Pr(>|t|)"])
}

apply(p, 2, function(x) length(which(x<0.05)))/niter
```

```{r lmm1-BG_biomass, echo=FALSE}
folder <- "Data from Data from Above and below ground responses of four tundra plant functional types to deep soil heating and surface soil fertilization"
fn <- "2015.04.15_weighing results belowground.xlsx"
file_path <- paste(data_path, folder, fn, sep="/")
BG_biomass <- data.table(read_excel(file_path, range="A1:H875"))
BG_biomass[, log_weight:=log(weight)]
BG_biomass[, log_weight_p1:=log(weight+1)]

# make block and pft factors
BG_biomass[, block:=factor(block)]
BG_biomass[, pft:=factor(pft)]

# change plot to unique labels so that labels differ among blocks
BG_biomass[, plot2 :=factor(paste(block,plot,sep='-'))]

# heating levels
# C - "control", PC - "cable", or procedural control, H=warming
heating_levels <- c("C", "PC", "H")
# fertlization levels
# C - "control"
# F - "fertilized"
fertlization_levels <- c("C", "F")
BG_biomass[, Heating:=ifelse(plot==3 | plot==4, "C",
               ifelse(plot==2 | plot==6, "PC",
               ifelse(plot==1 | plot==5, "H", NA))
                      )]
BG_biomass[, Heating:=factor(Heating, heating_levels)]
BG_biomass[, Fertilization:=ifelse(plot %in% c(2, 4, 5), "C", "F")]
BG_biomass[, Fertilization:=factor(Fertilization, fertlization_levels)]

# combine C + PC
BG_biomass[, Heating2:=ifelse(as.character(Heating)=="PC", "C", as.character(Heating))]
BG_biomass[, Heating2:=factor(Heating2)]

# layer
# 1: 0-5cm
# 2: 5-15cm
# 3: 15-30cm
# 4: below 30cm
# 
# 
# part
# cr: coarse root
# fr: fine root
# rh: rhizome/ belowground stem
```

```{r lmm1-bg-biomass-model, echo=FALSE, eval=TRUE}

inc <- which(BG_biomass$tissue=="fr")
inc <- 1:nrow(BG_biomass)

fit1 <- lmer(log_weight ~ Heating*Fertilization*pft + (1|plot2), data=BG_biomass[inc])
anova(fit1)

fit2 <- lmer(log_weight ~ Heating*Fertilization*pft + (1|block/plot2), data=BG_biomass[inc])
anova(fit2)

fit3 <- lmer(log_weight_p1 ~ Heating*Fertilization*pft + (1|block/plot2), data=BG_biomass[inc])
anova(fit3)

# note there is only 1 df for the Heating treatment, were PC + C combined?
# remove cable
fit4 <- lmer(log_weight ~ Heating*Fertilization*pft + (1|block/plot2), 
             data=BG_biomass[Heating!="PC"])
anova(fit4)

# remove control?
fit4b <- lmer(log_weight ~ Heating*Fertilization*pft + (1|block/plot2), 
             data=BG_biomass[Heating!="C"])
anova(fit4b)

fit5 <- lmer(log_weight_p1 ~ Heating2*Fertilization*pft + (1|block/plot2), data=BG_biomass[inc])
anova(fit5)
anova(fit5, type=2)
anova(fit5, type=1)

fit6 <- lmer(log_weight ~ Heating2*Fertilization*pft + (1|block/plot2), data=BG_biomass[inc])
anova(fit6)
anova(fit6, ddf="Kenward-Roger")



```

