---
title: "dolman simulation"
author: "Jeff Walker"
date: "10/17/2019"
output: html_document
---

Macrophyte effects on algal turbidity in subtropical versus temperate lakes: a comment on Wang et al.(2014)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(ggpubr)
```

```{r}
set.seed(2)
mu_x0 <- 1.4
mu_x1 <- 2.3
sigma_x <- .3
sigma_y <- 0.3
beta_0 <- -0.05
beta_1 <- 0.35 # slope
beta_2 <- 0 # treatment
beta_3 <- 0.25 # interaction
beta <- c(beta_0, beta_1, beta_2, beta_3)
n <- 44

done <- FALSE
tol <- 0.01
seed_i <- 0 #7413
seed_i <- 7412
while(done==FALSE){
  seed_i <- seed_i+1
  set.seed(seed_i)
  fd <- data.table(
    treatment = rep(c("present", "absent"), each=n),
    logTP = c(rnorm(n, mu_x0, sigma_x), rnorm(n, mu_x1, sigma_x))
  )
  fd[, treatment:=factor(treatment, c("present", "absent"))]
  X <- model.matrix(~ logTP*treatment, data=fd)
  fd[, logChla:=(X%*%beta)[,1] + rnorm(n*2, sd=sigma_y)]
  m1 <- coef(lm(logChla ~ logTP*treatment, data=fd))
  if(abs(m1[2] - beta[2]) < tol &
     abs(m1[3] - beta[3]) < tol &
     abs(m1[4] - beta[4]) < tol){done <- TRUE}
}
qplot(data=fd, x=logTP, y=logChla, color=treatment) + geom_smooth(method="lm")
m1 <- lm(logChla ~ logTP*treatment, data=fd)
m2 <- lm(logChla ~ logTP + treatment, data=fd)
m3 <- lm(logChla ~ logTP, data=fd)
anova(m1, m2)
anova(m2, m3)
anova(m1, m3)
coef(summary(m1))
coef(summary(m2))

```

